import React, { useState, useEffect } from 'react';
import { 
  Shield, Key, Lock, Unlock, Globe, Server, CheckCircle2, AlertTriangle, 
  XCircle, RefreshCw, Terminal as TermIcon, Play, Copy, Check, Eye, EyeOff,
  Cpu, Zap, Sparkles, Filter, ArrowUpRight, Activity, Database, FileSpreadsheet
} from 'lucide-react';
import { TheVaultManager, RestEndpointDefinition, VaultKeyPair, VaultAuditLogEntry } from '../lib/VaultManager';
import { WasmIsolateVM } from '../lib/WasmIsolateVM';

interface VaultManagerAppProps {
  addNotification: (title: string, message: string, type?: 'info' | 'success' | 'warning' | 'error') => void;
  openWindow?: (appId: string, title?: string) => void;
}

export function VaultManagerApp({ addNotification, openWindow }: VaultManagerAppProps) {
  const [activeTab, setActiveTab] = useState<'endpoints' | 'keys' | 'tester' | 'audit' | 'isolate'>('endpoints');
  const [endpoints, setEndpoints] = useState<RestEndpointDefinition[]>([]);
  const [keyPairs, setKeyPairs] = useState<VaultKeyPair[]>([]);
  const [auditLogs, setAuditLogs] = useState<VaultAuditLogEntry[]>([]);
  const [selectedEndpoint, setSelectedEndpoint] = useState<RestEndpointDefinition | null>(null);
  
  // Binding modal/action state
  const [targetInterface, setTargetInterface] = useState<'127.0.0.1' | '0.0.0.0' | '192.168.1.105 (eth0)' | '10.0.0.42 (wlan0)'>('0.0.0.0');
  const [targetPort, setTargetPort] = useState<number>(8080);
  const [selectedKeyForSigning, setSelectedKeyForSigning] = useState<string>('VAULT_SIGNING_KEY_ALPHA');

  // API Playground State
  const [testEndpointId, setTestEndpointId] = useState<string>('');
  const [testMethod, setTestMethod] = useState<string>('GET');
  const [includeVaultHeader, setIncludeVaultHeader] = useState<boolean>(true);
  const [testResponse, setTestResponse] = useState<any>(null);
  const [testLoading, setTestLoading] = useState<boolean>(false);
  const [copiedToken, setCopiedToken] = useState<string | null>(null);

  // New endpoint generator modal
  const [showNewEpModal, setShowNewEpModal] = useState(false);
  const [newEpName, setNewEpName] = useState('');
  const [newEpPath, setNewEpPath] = useState('/api/v1/custom/endpoint');
  const [newEpSource, setNewEpSource] = useState<'database_collection' | 'glasssheets_range' | 'system_kernel' | 'lanbridge_relay'>('database_collection');
  const [newEpTarget, setNewEpTarget] = useState('inventory_collection');

  const refreshData = () => {
    const eps = TheVaultManager.getEndpoints();
    setEndpoints(eps);
    setKeyPairs(TheVaultManager.getKeyPairs());
    setAuditLogs(TheVaultManager.getAuditLogs());
    if (eps.length > 0 && !testEndpointId) {
      setTestEndpointId(eps[0].id);
    }
  };

  useEffect(() => {
    refreshData();
    const interval = setInterval(refreshData, 3000);
    return () => clearInterval(interval);
  }, []);

  const handleSignEndpoint = (endpointId: string) => {
    const res = TheVaultManager.signEndpoint(endpointId, selectedKeyForSigning);
    if (res.success) {
      addNotification('The Vault Manager', `Cryptographic signature issued for endpoint! Token: ${res.signatureToken?.slice(0, 20)}...`, 'success');
      refreshData();
    } else {
      addNotification('The Vault Manager', res.error || 'Failed to sign endpoint', 'error');
    }
  };

  const handleBindEndpoint = (endpointId: string) => {
    const res = TheVaultManager.bindEndpoint(endpointId, targetInterface, targetPort);
    if (res.success) {
      addNotification('The Vault Manager', res.message || 'Endpoint bound successfully', 'success');
      refreshData();
    } else {
      addNotification('The Vault Security Intercept', res.error || 'Binding rejected by Vault policy', 'error');
      refreshData();
    }
  };

  const handleUnbindEndpoint = (endpointId: string) => {
    TheVaultManager.unbindEndpoint(endpointId);
    addNotification('The Vault Manager', 'Endpoint unbound from network interface', 'info');
    refreshData();
  };

  const handleRevokeSignature = (endpointId: string) => {
    TheVaultManager.revokeSignature(endpointId);
    addNotification('The Vault Manager', 'Endpoint cryptographic signature revoked. Open bindings purged.', 'warning');
    refreshData();
  };

  const handleCreateEndpoint = () => {
    if (!newEpName || !newEpPath) return;
    TheVaultManager.registerAutoGeneratedEndpoint({
      name: newEpName,
      path: newEpPath,
      method: 'ALL',
      source: newEpSource,
      sourceTarget: newEpTarget,
      boundInterface: 'UNBOUND',
      port: targetPort,
      isPublicInterface: false,
      rateLimitPerMin: 120,
      description: `Auto-generated REST endpoint from ${newEpSource} (${newEpTarget}).`
    });
    setShowNewEpModal(false);
    setNewEpName('');
    addNotification('The Vault Manager', 'Auto-generated REST endpoint registered in unsigned state', 'info');
    refreshData();
  };

  const handleExecuteTest = () => {
    if (!testEndpointId) return;
    setTestLoading(true);
    setTestResponse(null);

    const ep = endpoints.find(e => e.id === testEndpointId);
    const headers: Record<string, string> = {
      'Content-Type': 'application/json'
    };

    if (includeVaultHeader && ep?.signatureToken) {
      headers['Authorization'] = `Bearer ${ep.signatureToken}`;
      headers['X-Vault-Signature'] = ep.signatureToken;
      headers['X-Vault-KeyId'] = ep.signedByVaultKeyId || 'VAULT_ROOT';
    }

    setTimeout(() => {
      const res = TheVaultManager.simulateRequest(testEndpointId, {
        method: testMethod,
        headers
      });
      setTestResponse(res);
      setTestLoading(false);
      refreshData();
    }, 250);
  };

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard?.writeText(text);
    setCopiedToken(id);
    setTimeout(() => setCopiedToken(null), 2000);
    addNotification('The Vault Manager', 'Signature token copied to clipboard', 'info');
  };

  return (
    <div className="h-full flex flex-col bg-[#030712] text-white font-sans overflow-hidden">
      {/* Top Banner Header */}
      <div className="p-4 bg-slate-900/90 border-b border-white/10 backdrop-blur-md flex items-center justify-between shadow-lg">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-gradient-to-br from-amber-500/20 to-yellow-600/20 border border-amber-500/30 text-amber-400 shadow-[0_0_15px_rgba(245,158,11,0.2)]">
            <Shield size={24} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-lg font-bold tracking-tight text-white flex items-center gap-2">
                The Vault Manager
                <span className="px-2 py-0.5 rounded text-[9px] font-mono font-bold bg-amber-500/20 text-amber-300 border border-amber-500/30">
                  CRYPTOGRAPHIC REST GATEWAY
                </span>
              </h1>
            </div>
            <p className="text-[11px] text-white/50 font-mono">
              Enforcing signature verification on auto-generated REST endpoints & sandboxed isolates
            </p>
          </div>
        </div>

        {/* Tab Navigation */}
        <div className="flex items-center gap-1 bg-white/5 p-1 rounded-xl border border-white/10">
          {[
            { id: 'endpoints', label: 'REST Endpoints', icon: <Server size={13} /> },
            { id: 'keys', label: 'Vault Keys & Certs', icon: <Key size={13} /> },
            { id: 'tester', label: 'API Playground', icon: <Play size={13} /> },
            { id: 'isolate', label: 'Wasm/V8 Quotas', icon: <Cpu size={13} /> },
            { id: 'audit', label: 'Security Log', icon: <Activity size={13} /> }
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all ${
                activeTab === tab.id
                  ? 'bg-amber-500 text-slate-950 font-bold shadow-[0_0_10px_rgba(245,158,11,0.4)]'
                  : 'text-white/60 hover:text-white hover:bg-white/5'
              }`}
            >
              {tab.icon}
              <span>{tab.label}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 overflow-y-auto p-5 custom-scrollbar space-y-5">
        {/* TAB 1: REST Endpoints */}
        {activeTab === 'endpoints' && (
          <div className="space-y-5">
            {/* Top Stat Bar */}
            <div className="grid grid-cols-4 gap-4">
              <div className="p-4 rounded-2xl bg-white/[0.03] border border-white/10 flex items-center justify-between">
                <div>
                  <span className="text-[10px] uppercase font-mono text-white/40 font-bold">Total REST Endpoints</span>
                  <div className="text-2xl font-mono font-bold text-white mt-1">{endpoints.length}</div>
                </div>
                <div className="p-2.5 rounded-xl bg-blue-500/10 text-blue-400 border border-blue-500/20">
                  <Server size={18} />
                </div>
              </div>

              <div className="p-4 rounded-2xl bg-white/[0.03] border border-white/10 flex items-center justify-between">
                <div>
                  <span className="text-[10px] uppercase font-mono text-white/40 font-bold">Vault Signed & Verified</span>
                  <div className="text-2xl font-mono font-bold text-emerald-400 mt-1">
                    {endpoints.filter(e => e.signatureStatus === 'VERIFIED_SIGNED').length}
                  </div>
                </div>
                <div className="p-2.5 rounded-xl bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                  <CheckCircle2 size={18} />
                </div>
              </div>

              <div className="p-4 rounded-2xl bg-white/[0.03] border border-white/10 flex items-center justify-between">
                <div>
                  <span className="text-[10px] uppercase font-mono text-white/40 font-bold">Open Interface Bindings</span>
                  <div className="text-2xl font-mono font-bold text-amber-400 mt-1">
                    {endpoints.filter(e => e.isPublicInterface).length}
                  </div>
                </div>
                <div className="p-2.5 rounded-xl bg-amber-500/10 text-amber-400 border border-amber-500/20">
                  <Globe size={18} />
                </div>
              </div>

              <div className="p-4 rounded-2xl bg-white/[0.03] border border-white/10 flex items-center justify-between">
                <div>
                  <span className="text-[10px] uppercase font-mono text-white/40 font-bold">Security Enforcement</span>
                  <div className="text-sm font-mono font-bold text-emerald-400 mt-2 flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                    VAULT STRICT
                  </div>
                </div>
                <div className="p-2.5 rounded-xl bg-purple-500/10 text-purple-400 border border-purple-500/20">
                  <Lock size={18} />
                </div>
              </div>
            </div>

            {/* Actions Bar */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="text-xs text-white/60 font-mono">Policy:</span>
                <span className="text-xs px-2.5 py-1 rounded-lg bg-red-500/10 text-red-300 border border-red-500/20 font-mono font-medium flex items-center gap-1.5">
                  <Lock size={12} />
                  Open Interface Bindings (0.0.0.0/LAN) REQUIRE Valid Vault Signatures
                </span>
              </div>
              <button
                onClick={() => setShowNewEpModal(true)}
                className="px-3.5 py-1.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold text-xs flex items-center gap-1.5 transition-all shadow-md"
              >
                <Sparkles size={13} />
                Generate New REST Endpoint
              </button>
            </div>

            {/* Endpoints List Cards */}
            <div className="grid grid-cols-1 gap-3.5">
              {endpoints.map(ep => (
                <div 
                  key={ep.id}
                  className={`p-4 rounded-2xl border transition-all ${
                    ep.signatureStatus === 'VERIFIED_SIGNED'
                      ? 'bg-slate-900/60 border-emerald-500/30 shadow-[0_0_15px_rgba(16,185,129,0.05)]'
                      : ep.signatureStatus === 'REVOKED'
                      ? 'bg-red-950/20 border-red-500/30'
                      : 'bg-slate-900/40 border-white/10'
                  }`}
                >
                  <div className="flex items-start justify-between gap-4">
                    <div className="space-y-1.5 flex-1">
                      <div className="flex items-center gap-2.5 flex-wrap">
                        <span className="text-xs font-bold px-2 py-0.5 rounded bg-blue-500/20 text-blue-300 border border-blue-500/30 font-mono">
                          {ep.method}
                        </span>
                        <span className="font-mono text-sm font-bold text-white tracking-wide">{ep.path}</span>
                        
                        {/* Signature Status Badge */}
                        {ep.signatureStatus === 'VERIFIED_SIGNED' ? (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 font-mono font-bold flex items-center gap-1">
                            <CheckCircle2 size={11} />
                            VAULT-SIGNED & VERIFIED
                          </span>
                        ) : ep.signatureStatus === 'REVOKED' ? (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-red-500/20 text-red-300 border border-red-500/40 font-mono font-bold flex items-center gap-1">
                            <XCircle size={11} />
                            SIGNATURE REVOKED
                          </span>
                        ) : (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-yellow-500/20 text-yellow-300 border border-yellow-500/40 font-mono font-bold flex items-center gap-1">
                            <AlertTriangle size={11} />
                            UNSIGNED (Local Only)
                          </span>
                        )}

                        {/* Interface Badge */}
                        <span className={`text-[10px] px-2 py-0.5 rounded-full font-mono font-bold flex items-center gap-1 ${
                          ep.boundInterface === 'UNBOUND'
                            ? 'bg-slate-800 text-white/40 border border-white/10'
                            : ep.isPublicInterface
                            ? 'bg-purple-500/20 text-purple-300 border border-purple-500/40'
                            : 'bg-blue-500/10 text-blue-300 border border-blue-500/20'
                        }`}>
                          <Globe size={11} />
                          {ep.boundInterface === 'UNBOUND' ? 'UNBOUND' : `${ep.boundInterface}:${ep.port}`}
                        </span>
                      </div>

                      <p className="text-xs text-white/70">{ep.description}</p>

                      <div className="flex items-center gap-4 text-[11px] text-white/40 font-mono pt-1 flex-wrap">
                        <span>Source: <strong className="text-white/70">{ep.source} ({ep.sourceTarget})</strong></span>
                        <span>Requests: <strong className="text-white/70">{ep.totalRequests}</strong></span>
                        <span>Rate Limit: <strong className="text-white/70">{ep.rateLimitPerMin} req/min</strong></span>
                        {ep.signedByVaultKeyId && (
                          <span>Signed By: <strong className="text-amber-300/80">{ep.signedByVaultKeyId}</strong></span>
                        )}
                      </div>

                      {/* Signature Token Preview */}
                      {ep.signatureToken && (
                        <div className="mt-2 p-2 rounded-xl bg-black/40 border border-white/5 flex items-center justify-between text-[10px] font-mono text-white/60">
                          <div className="truncate flex-1 pr-2">
                            <span className="text-amber-400 font-bold">X-Vault-Signature:</span> {ep.signatureToken}
                          </div>
                          <button
                            onClick={() => copyToClipboard(ep.signatureToken!, ep.id)}
                            className="p-1 rounded hover:bg-white/10 text-white/60 hover:text-white transition-all shrink-0"
                            title="Copy Signature Token"
                          >
                            {copiedToken === ep.id ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
                          </button>
                        </div>
                      )}
                    </div>

                    {/* Action Controls */}
                    <div className="flex flex-col gap-2 shrink-0 items-end">
                      {ep.signatureStatus !== 'VERIFIED_SIGNED' ? (
                        <button
                          onClick={() => handleSignEndpoint(ep.id)}
                          className="px-3 py-1.5 rounded-xl bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 border border-amber-500/40 text-xs font-bold flex items-center gap-1.5 transition-all"
                        >
                          <Key size={12} />
                          Sign with Vault Key
                        </button>
                      ) : (
                        <button
                          onClick={() => handleRevokeSignature(ep.id)}
                          className="px-2.5 py-1 rounded-lg bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/30 text-[10px] font-bold flex items-center gap-1 transition-all"
                        >
                          <Lock size={11} />
                          Revoke Signature
                        </button>
                      )}

                      {ep.boundInterface === 'UNBOUND' ? (
                        <div className="flex items-center gap-1.5">
                          <select
                            value={targetInterface}
                            onChange={(e) => setTargetInterface(e.target.value as any)}
                            className="bg-slate-800 text-[10px] font-mono text-white/80 border border-white/10 rounded-lg px-2 py-1 outline-none"
                          >
                            <option value="127.0.0.1">127.0.0.1 (Loopback)</option>
                            <option value="0.0.0.0">0.0.0.0 (Open All)</option>
                            <option value="192.168.1.105 (eth0)">192.168.1.105 (eth0)</option>
                            <option value="10.0.0.42 (wlan0)">10.0.0.42 (wlan0)</option>
                          </select>
                          <button
                            onClick={() => handleBindEndpoint(ep.id)}
                            className="px-3 py-1 rounded-lg bg-blue-500/20 hover:bg-blue-500/30 text-blue-300 border border-blue-500/40 text-[11px] font-bold flex items-center gap-1 transition-all"
                          >
                            <Globe size={12} />
                            Bind Interface
                          </button>
                        </div>
                      ) : (
                        <button
                          onClick={() => handleUnbindEndpoint(ep.id)}
                          className="px-3 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-white/70 text-[11px] font-mono flex items-center gap-1 transition-all border border-white/10"
                        >
                          Unbind
                        </button>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* TAB 2: Vault Keys & Certificates */}
        {activeTab === 'keys' && (
          <div className="space-y-5">
            <div className="p-4 rounded-2xl bg-amber-500/5 border border-amber-500/20 space-y-2">
              <div className="flex items-center gap-2 text-amber-300 font-bold text-sm">
                <Key size={16} />
                The Vault Root Certificate Authority (CA) & Signing Hierarchy
              </div>
              <p className="text-xs text-white/70 leading-relaxed">
                The Vault Manager maintains hardware-isolated asymmetric cryptographic keys (ECDSA P-256 & RSA-PSS 2048). 
                All auto-generated REST endpoints attempting network exposure undergo signature verification before socket binding.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {keyPairs.map(key => (
                <div key={key.keyId} className="p-5 rounded-2xl bg-slate-900/60 border border-white/10 space-y-4 shadow-lg">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <div className="p-2 rounded-lg bg-amber-500/10 text-amber-400 border border-amber-500/20">
                        <Key size={16} />
                      </div>
                      <div>
                        <div className="font-mono font-bold text-sm text-white">{key.keyId}</div>
                        <div className="text-[10px] font-mono text-white/40">{key.algorithm}</div>
                      </div>
                    </div>
                    <span className="px-2 py-0.5 rounded text-[9px] font-mono font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40">
                      {key.status}
                    </span>
                  </div>

                  <div className="space-y-1 text-xs font-mono">
                    <div className="text-[10px] text-white/40 uppercase">Fingerprint (SHA256)</div>
                    <div className="p-2 rounded-xl bg-black/40 text-[10px] text-amber-200/90 break-all border border-white/5">
                      {key.fingerprint}
                    </div>
                  </div>

                  <div className="space-y-1 text-xs font-mono">
                    <div className="text-[10px] text-white/40 uppercase">Public Key Certificate (PEM)</div>
                    <pre className="p-2.5 rounded-xl bg-black/60 text-[9px] text-white/50 overflow-x-auto border border-white/5 font-mono">
                      {key.publicKeyPem}
                    </pre>
                  </div>

                  <div className="flex items-center justify-between text-[10px] font-mono text-white/40 pt-2 border-t border-white/5">
                    <span>Created: {key.createdAt}</span>
                    <span>Expires: {key.expiresAt}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* TAB 3: API Playground / Request Tester */}
        {activeTab === 'tester' && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
            {/* Request Builder */}
            <div className="p-5 rounded-2xl bg-slate-900/60 border border-white/10 space-y-4">
              <h3 className="text-sm font-bold text-white flex items-center gap-2">
                <Play size={14} className="text-amber-400" />
                REST Request Simulator & Vault Verifier
              </h3>

              <div className="space-y-3">
                <div>
                  <label className="text-[10px] uppercase font-mono text-white/40 font-bold">Select Target Endpoint</label>
                  <select
                    value={testEndpointId}
                    onChange={(e) => setTestEndpointId(e.target.value)}
                    className="w-full bg-slate-800 text-xs text-white border border-white/10 rounded-xl p-2.5 mt-1 outline-none font-mono"
                  >
                    {endpoints.map(ep => (
                      <option key={ep.id} value={ep.id}>
                        {ep.method} {ep.path} ({ep.boundInterface === 'UNBOUND' ? 'UNBOUND' : ep.boundInterface})
                      </option>
                    ))}
                  </select>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-[10px] uppercase font-mono text-white/40 font-bold">HTTP Method</label>
                    <select
                      value={testMethod}
                      onChange={(e) => setTestMethod(e.target.value)}
                      className="w-full bg-slate-800 text-xs text-white border border-white/10 rounded-xl p-2.5 mt-1 outline-none font-mono"
                    >
                      <option value="GET">GET</option>
                      <option value="POST">POST</option>
                      <option value="PUT">PUT</option>
                      <option value="DELETE">DELETE</option>
                    </select>
                  </div>

                  <div className="flex flex-col justify-end">
                    <label className="flex items-center gap-2 p-2.5 rounded-xl bg-white/5 border border-white/10 cursor-pointer hover:bg-white/10 transition-all text-xs">
                      <input
                        type="checkbox"
                        checked={includeVaultHeader}
                        onChange={(e) => setIncludeVaultHeader(e.target.checked)}
                        className="rounded accent-amber-500"
                      />
                      <span className="font-mono text-[11px]">Include Vault Sig Header</span>
                    </label>
                  </div>
                </div>

                <button
                  onClick={handleExecuteTest}
                  disabled={testLoading || !testEndpointId}
                  className="w-full py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold text-xs flex items-center justify-center gap-2 transition-all shadow-md disabled:opacity-50"
                >
                  {testLoading ? <RefreshCw size={14} className="animate-spin" /> : <Play size={14} fill="currentColor" />}
                  Dispatch Test Request
                </button>
              </div>
            </div>

            {/* Response Viewer */}
            <div className="p-5 rounded-2xl bg-slate-900/60 border border-white/10 space-y-3 flex flex-col">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-bold text-white flex items-center gap-2">
                  <Activity size={14} className="text-blue-400" />
                  Live Response
                </h3>
                {testResponse && (
                  <span className={`text-[10px] font-mono px-2 py-0.5 rounded font-bold ${
                    testResponse.status === 200
                      ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                      : 'bg-red-500/20 text-red-300 border border-red-500/30'
                  }`}>
                    HTTP {testResponse.status}
                  </span>
                )}
              </div>

              <div className="flex-1 bg-black/60 rounded-xl p-3 border border-white/5 font-mono text-xs overflow-y-auto max-h-[340px]">
                {testResponse ? (
                  <pre className="text-[11px] text-emerald-400/90 whitespace-pre-wrap">
                    {JSON.stringify(testResponse, null, 2)}
                  </pre>
                ) : (
                  <div className="h-full flex items-center justify-center text-white/30 text-xs italic">
                    Press "Dispatch Test Request" to simulate a live REST call against the endpoint.
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* TAB 4: Wasm / V8 Isolate & Quotas */}
        {activeTab === 'isolate' && (
          <div className="space-y-5">
            <div className="p-4 rounded-2xl bg-purple-500/10 border border-purple-500/20 space-y-2">
              <div className="flex items-center gap-2 text-purple-300 font-bold text-sm">
                <Cpu size={16} />
                WebAssembly & V8 Isolate Sandboxing & Denial-of-Service Quotas
              </div>
              <p className="text-xs text-white/70 leading-relaxed">
                Raw string evaluation (`eval`/`Function`) is strictly prohibited. All sheet formulas, User Defined Functions (UDFs),
                and document `onCompute` hooks execute inside hardened WebAssembly isolates with deterministic cycle caps (gas limits)
                and instruction step counters.
              </p>
            </div>

            {/* Registered UDFs List */}
            <div className="space-y-3">
              <h3 className="text-xs font-mono uppercase font-bold text-white/50 tracking-wider">
                Active Sandboxed User Defined Functions (UDFs)
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                {WasmIsolateVM.getUDFs().map(udf => (
                  <div key={udf.name} className="p-4 rounded-xl bg-slate-900/60 border border-white/10 space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="font-mono font-bold text-xs text-amber-300">{udf.name}</span>
                      <span className="text-[9px] px-1.5 py-0.5 rounded bg-white/5 text-white/40 font-mono">ISOLATED</span>
                    </div>
                    <div className="text-[11px] font-mono text-purple-300 bg-black/40 p-1.5 rounded border border-white/5">
                      ({udf.params.join(', ')}) =&gt; {udf.body}
                    </div>
                    <p className="text-[10px] text-white/60">{udf.description}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Registered onCompute Hooks */}
            <div className="space-y-3">
              <h3 className="text-xs font-mono uppercase font-bold text-white/50 tracking-wider">
                Active onCompute Hooks & Cycle Budgets
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {WasmIsolateVM.getOnComputeHooks().map(hook => (
                  <div key={hook.id} className="p-4 rounded-xl bg-slate-900/60 border border-white/10 space-y-3">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-xs text-white">{hook.name}</span>
                      <span className="text-[10px] px-2 py-0.5 rounded-full font-mono bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                        {hook.trigger}
                      </span>
                    </div>
                    <div className="text-[11px] font-mono text-blue-300 bg-black/40 p-2 rounded border border-white/5">
                      {hook.script}
                    </div>
                    <div className="flex items-center justify-between text-[10px] font-mono text-white/50">
                      <span>Cycle Limit: <strong className="text-amber-300">{hook.cycleLimit}</strong></span>
                      <span>Last Run: <strong className="text-emerald-300">{hook.lastExecution?.cyclesUsed || 0} cycles ({hook.lastExecution?.status || 'IDLE'})</strong></span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* TAB 5: Security Audit Log */}
        {activeTab === 'audit' && (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-mono uppercase font-bold text-white/50 tracking-wider">
                Real-Time Security & Signature Verification Stream
              </h3>
              <button
                onClick={refreshData}
                className="px-2.5 py-1 rounded-lg bg-white/5 hover:bg-white/10 text-white/60 hover:text-white text-[10px] font-mono flex items-center gap-1 transition-all"
              >
                <RefreshCw size={11} /> Refresh
              </button>
            </div>

            <div className="space-y-2">
              {auditLogs.map(log => (
                <div 
                  key={log.id}
                  className={`p-3 rounded-xl border text-xs font-mono flex items-start gap-3 transition-all ${
                    log.severity === 'CRITICAL'
                      ? 'bg-red-950/20 border-red-500/30 text-red-200'
                      : log.severity === 'SUCCESS'
                      ? 'bg-emerald-950/20 border-emerald-500/30 text-emerald-200'
                      : log.severity === 'WARN'
                      ? 'bg-amber-950/20 border-amber-500/30 text-amber-200'
                      : 'bg-slate-900/50 border-white/10 text-white/80'
                  }`}
                >
                  <div className="p-1 rounded bg-black/40 shrink-0 mt-0.5">
                    {log.severity === 'CRITICAL' ? (
                      <XCircle size={14} className="text-red-400" />
                    ) : log.severity === 'SUCCESS' ? (
                      <CheckCircle2 size={14} className="text-emerald-400" />
                    ) : (
                      <AlertTriangle size={14} className="text-amber-400" />
                    )}
                  </div>
                  <div className="flex-1 space-y-0.5">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-[11px] tracking-wide">{log.event}</span>
                      <span className="text-[10px] text-white/40">{log.timestamp}</span>
                    </div>
                    <p className="text-[11px] text-white/70 leading-relaxed">{log.details}</p>
                    {log.endpointPath && (
                      <div className="text-[10px] text-white/40">Target: {log.endpointPath}</div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* New Endpoint Modal */}
      {showNewEpModal && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="w-full max-w-md p-6 rounded-2xl bg-slate-900 border border-white/15 shadow-2xl space-y-4">
            <h2 className="text-base font-bold text-white flex items-center gap-2">
              <Server size={16} className="text-amber-400" />
              Register Auto-Generated REST Endpoint
            </h2>

            <div className="space-y-3 text-xs">
              <div>
                <label className="text-[10px] font-mono uppercase text-white/40 font-bold">Endpoint Name</label>
                <input
                  type="text"
                  value={newEpName}
                  onChange={(e) => setNewEpName(e.target.value)}
                  placeholder="e.g. Products Inventory API"
                  className="w-full bg-slate-800 text-white rounded-xl p-2.5 mt-1 border border-white/10 outline-none font-sans"
                />
              </div>

              <div>
                <label className="text-[10px] font-mono uppercase text-white/40 font-bold">REST Route Path</label>
                <input
                  type="text"
                  value={newEpPath}
                  onChange={(e) => setNewEpPath(e.target.value)}
                  placeholder="/api/v1/database/products"
                  className="w-full bg-slate-800 text-white rounded-xl p-2.5 mt-1 border border-white/10 outline-none font-mono text-xs"
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="text-[10px] font-mono uppercase text-white/40 font-bold">Data Source</label>
                  <select
                    value={newEpSource}
                    onChange={(e) => setNewEpSource(e.target.value as any)}
                    className="w-full bg-slate-800 text-white rounded-xl p-2.5 mt-1 border border-white/10 outline-none font-mono"
                  >
                    <option value="database_collection">GlassDatabase Collection</option>
                    <option value="glasssheets_range">GlassSheets Range</option>
                    <option value="system_kernel">System Kernel RPC</option>
                    <option value="lanbridge_relay">LAN Bridge Relay</option>
                  </select>
                </div>
                <div>
                  <label className="text-[10px] font-mono uppercase text-white/40 font-bold">Source Target</label>
                  <input
                    type="text"
                    value={newEpTarget}
                    onChange={(e) => setNewEpTarget(e.target.value)}
                    placeholder="table_name or Range"
                    className="w-full bg-slate-800 text-white rounded-xl p-2.5 mt-1 border border-white/10 outline-none font-mono"
                  />
                </div>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2 border-t border-white/10">
              <button
                onClick={() => setShowNewEpModal(false)}
                className="px-4 py-2 rounded-xl bg-white/5 hover:bg-white/10 text-white/70 text-xs font-semibold"
              >
                Cancel
              </button>
              <button
                onClick={handleCreateEndpoint}
                className="px-4 py-2 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 text-xs font-bold transition-all"
              >
                Create Endpoint
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
